# Generated by Django 6.0.2 on 2026-02-11 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanKantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_staf', models.CharField(help_text='Misal: Andi', max_length=100)),
                ('deskripsi', models.TextField(help_text='Apa yang dikerjakan')),
                ('foto_hasil', models.ImageField(blank=True, null=True, upload_to='hasil_kantor/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaporanLapangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tim', models.CharField(help_text='Misal: Tim Alpha', max_length=100)),
                ('penerima', models.CharField(help_text='Misal: Pak Budi', max_length=100)),
                ('alamat', models.TextField()),
                ('jarak_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('keterangan', models.TextField()),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Submitted', max_length=20)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoLaporanLapangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.ImageField(upload_to='bukti_lapangan/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foto_bukti', to='laporan.laporanlapangan')),
            ],
        ),
    ]
